export enum JOB_STATUS {
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
}

export enum USER_TYPE {
  MASTER = 'MASTER',
  USER = 'USER',
  MANAGER = 'MANAGER',
}

export enum JOB_TYPES {
  ADD_FEEDS = 'ADD_FEEDS',
  UPDATE_FEEDS = 'UPDATE_FEEDS',
}
